✨Feat: 파일 업로드 기능 추가
star-toy/pollhub-backend pull request #24
Opened 2024-09-18 06:10 UTC by seeun-rosy-park

# PollHub
# ✨Feat: 파일 업로드 기능 추가

2024-09-18 06:58 UTC, hannal commented on src/main/java/com/startoy/pollhub/adapter/controller/FileStorageController.java
> +        if (file == null || file.isEmpty()) {
제한하는 최대 파일 용량도 필요하지 않을까요?

2024-09-18 06:59 UTC, hannal commented on src/main/java/com/startoy/pollhub/adapter/controller/FileStorageController.java
> +            return ResponseEntity.status(500).body(response);
모든 예외가 서버 문제인지 클라이언트 문제는 없는지 구분을 하면 어떨까요?
예를 들어, 허용하지 않는 파일을 업로드하는 경우는 400을 응답하는 거죠.

2024-09-18 07:02 UTC, hannal commented on src/main/java/com/startoy/pollhub/domain/Post.java
> +    @Column(name = "file_id", columnDefinition = "CHAR(36)")
이번에 구현할 사항은 아니며 기획을 정확히 알지 못하지만, 일반적으로는 Post 라면 File(Attachment)과 n:m 으로 하는 게 두고 두고 편하더라고요.

2024-09-18 07:02 UTC, hannal commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +    private final String uploadDir = "/path/to/upload/directory";
진짜 이 경로예요?

2024-09-18 07:03 UTC, seeun-rosy-park commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +    private final String uploadDir = "/path/to/upload/directory";
원래 어느 경로를 사용하나요..?

2024-09-18 07:05 UTC, hannal commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +        try {
try catch의 try 범위(scope)가 너무 넓어 보여요. 상황, 맥락 별로 exception을 받으면 의도가 더 명시적으로 드러나지 않을까요?

2024-09-18 07:06 UTC, hannal requested changes
자잘하고 사소하지만 수정이 필요한 게 있어서 변경요청 드립니다.

2024-09-18 07:06 UTC, hannal commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +    private final String uploadDir = "/path/to/upload/directory";
그런 의미로 드린 말씀은 아니고, 예제 코드에 있을 법한 경로명이어서요.

2024-09-18 11:56 UTC, seeun-rosy-park commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +    private final String uploadDir = "/path/to/upload/directory";
실무에서 사용할 법한 경로 추천해주시면 그렇게 사용하겠습니다!!

2024-09-18 12:10 UTC, seeun-rosy-park commented on src/main/java/com/startoy/pollhub/adapter/controller/FileStorageController.java
> +            return ResponseEntity.status(500).body(response);
[02ecb1d](https://github.com/star-toy/pollhub-backend/pull/24/commits/02ecb1dfee2bfd46c5a3163c0df484f23c796f11)
리뷰 반영하였습니다! 확인 부탁드려요. 🙏

2024-09-18 12:10 UTC, seeun-rosy-park commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +        try {
[339a908](https://github.com/star-toy/pollhub-backend/pull/24/commits/339a908c339d84ca4a0464fa901432be9d8c036b)
리뷰 반영하였습니다. 확인 부탁드려요 🙏

2024-09-18 14:34 UTC, hannal commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +    private final String uploadDir = "/path/to/upload/directory";
AWS S3 가 아니라면 `uploads/%Y/%m/%d/` 이렇게 분절해가면 좋을 것 같아요. 오늘 올리면 `uploads/2024/9/18/hannal.png` 이렇게 되는 형식요.

2024-09-18 14:37 UTC, hannal commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +            String fileFullName = fileNameParts[0] + "_" + fileId + "." + fileExtension; // ex) filename_uuid.png
사소하고 간단하지만, 이렇게 + 연산하지 말고 좀 더 안전하게 합쳐보아요. concat 이나 join

2024-09-19 03:12 UTC, seeun-rosy-park commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +    private final String uploadDir = "/path/to/upload/directory";
[5867026](https://github.com/star-toy/pollhub-backend/pull/24/commits/58670267dbb36e3d87c5fca4b79f7058ceaa164c)
반영완료하였습니다. 조언해주셔서 감사합니다.

2024-09-19 03:13 UTC, seeun-rosy-park commented on src/main/java/com/startoy/pollhub/usecase/FileStorageService.java
> +            String fileFullName = fileNameParts[0] + "_" + fileId + "." + fileExtension; // ex) filename_uuid.png
[ef28fc9](https://github.com/star-toy/pollhub-backend/pull/24/commits/ef28fc94f4efb3acef81b4513a04d567778162cc)
보간법이 가독성이 좋아서 format() 사용하였습니다. 조언 감사합니다.

2024-09-19 03:13 UTC, merged